import Head from 'next/head';
import React from 'react';

function Header() {
  return (
    <Head>
      <title>FinInspect</title>
      <meta name='description' content='Generated by financial inspection app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
      <link href="/dist/main.css" rel="stylesheet"></link>
    </Head>
  );
}

export default Header;
